### ISSUE TITLE
Gnomic projection

### ISSUE THREAD

**Issue by ckbruns** [cmbruns/globeview7#11]
All great circles (e.g. the equator, lines of longitude, the day/night terminator) are straight lines. Imagine a light source at the center of the earth projecting an image of the earth onto a plane. Distortions are extreme at the edges of the map. No more than one hemisphere can be seen at one time.
![gnomonic1](https://user-images.githubusercontent.com/5731752/193333562-2a714c88-aeed-4025-9ef3-0317effc23eb.jpg)

**Comment by cmbruns** [comment]
Fixed in https://github.com/cmbruns/globeview7/commit/7b3a4693bfa10423a186d69db9ead37380268a64
