### ISSUE TITLE
Stereographic projection

### ISSUE THREAD

**Issue by ckbruns** [cmbruns/globeview7#15]
An azimuthal projection that is conformal (The correct shapes of small features are preserved. In other words, shapes are not distorted.).  Size distortions become large at the edges.
![stereographic1](https://user-images.githubusercontent.com/5731752/193334147-8197d7d5-46d9-4ff4-b142-7e45fabfbbc1.jpg)

**Comment by cmbruns** [comment]
Fixed in f3a10ba845bdc8e0cef6558489716d5af63541b6
