### ISSUE TITLE
Azimuthal Equal Area projection

### ISSUE THREAD

**Issue by ckbruns** [cmbruns/globeview7#9]
Relative areas of land masses are correct.
![az_eq_area1](https://user-images.githubusercontent.com/5731752/193333463-44939f64-a5c2-4fce-80be-6bead7577692.jpg)

**Comment by cmbruns** [comment]
Fixed in https://github.com/cmbruns/globeview7/commit/2889d120e4553e6b9f013c78355b5b9aace5c0a3
